openapi: 3.0.1
info:
  title: testApi
  description: API Definition of testApi
  version: 1.0.0
servers:
- url: http://localhost:8290/testapi
paths:
  /:
    get:
      responses:
        default:
          description: Default response
